"""empty message

Revision ID: c8d467ead100
Revises: 
Create Date: 2023-07-11 16:27:00.845485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8d467ead100'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campfire_stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('image1', sa.String(), nullable=False),
    sa.Column('image2', sa.String(), nullable=True),
    sa.Column('image3', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_campfire_stories')),
    sa.UniqueConstraint('title', name=op.f('uq_campfire_stories_title'))
    )
    op.create_table('drinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_drinks')),
    sa.UniqueConstraint('name', name=op.f('uq_drinks_name'))
    )
    op.create_table('snacks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_snacks')),
    sa.UniqueConstraint('name', name=op.f('uq_snacks_name'))
    )
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tokens'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('_password_hash', sa.String(), nullable=False),
    sa.Column('camper_name', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('rules', sa.Text(), nullable=False),
    sa.Column('win_status', sa.Boolean(), nullable=True),
    sa.Column('image1', sa.String(), nullable=False),
    sa.Column('image2', sa.String(), nullable=True),
    sa.Column('image3', sa.String(), nullable=True),
    sa.Column('image4', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['token_id'], ['tokens.id'], name=op.f('fk_games_token_id_tokens')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_games_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_games'))
    )
    op.create_table('lunch_boxes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('snack_id', sa.Integer(), nullable=True),
    sa.Column('drink_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['drink_id'], ['drinks.id'], name=op.f('fk_lunch_boxes_drink_id_drinks')),
    sa.ForeignKeyConstraint(['snack_id'], ['snacks.id'], name=op.f('fk_lunch_boxes_snack_id_snacks')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_lunch_boxes_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lunch_boxes'))
    )
    op.create_table('treasure_chests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_treasure_chests_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_treasure_chests'))
    )
    op.create_table('prizes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=False),
    sa.Column('token_price', sa.Integer(), nullable=False),
    sa.Column('treasure_chest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['treasure_chest_id'], ['treasure_chests.id'], name=op.f('fk_prizes_treasure_chest_id_treasure_chests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_prizes'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prizes')
    op.drop_table('treasure_chests')
    op.drop_table('lunch_boxes')
    op.drop_table('games')
    op.drop_table('users')
    op.drop_table('tokens')
    op.drop_table('snacks')
    op.drop_table('drinks')
    op.drop_table('campfire_stories')
    # ### end Alembic commands ###
